### ISSUE TITLE
Detect feeling from text

### ISSUE THREAD

**Issue by bennyz** [bennyz/feelings_bot#1]
There's probably an API out there that could help

**Comment by matanshukry** [comment]
Are we looking for a 1 word feeling text or sentence (or paragraphs)? how much text are we talking about here?

**Comment by bennyz** [comment]
Preferably a sentence, perhaps use some API that able to tell the feeling given a short text

**Comment by matanshukry** [comment]
https://medium.com/@sifium/top-five-emotional-sentiment-analysis-apis-116cd8d42055
Going to try Indico due to it's response format - sounds fitting.

**Comment by matanshukry** [comment]
Closing due to #4
